"""create categories and payment_methods tables

Revision ID: e861436284c1
Revises: 638e36f3763b
Create Date: 2026-08-04 07:42:45.767736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e861436284c1'
down_revision: Union[str, None] = '638e36f3763b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_name'), 'payment_methods', ['name'], unique=True)
    # ### end Alembic commands ###

    # フロントエンドが従来ハードコードしていた選択肢（expense-options-dummy-data.ts）を
    # 初期データとして投入し、既存のカテゴリ・支払方法の見た目を引き継ぐ。
    categories_table = sa.table("categories", sa.column("name", sa.String))
    op.bulk_insert(
        categories_table,
        [{"name": name} for name in ["食費", "交通費", "日用品", "医療費", "趣味", "その他"]],
    )

    payment_methods_table = sa.table("payment_methods", sa.column("name", sa.String))
    op.bulk_insert(
        payment_methods_table,
        [{"name": name} for name in ["現金", "PayPay", "楽天カード", "JCB", "銀行", "その他"]],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_methods_name'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
